name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
  job01:
  # if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:
    - name: say hello
  # if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
      run: |
        echo ${{ github.event.comment.body }}
    - name: test
      run: |
        echo test
